name: Python tests

on:
  [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Initialize Python environment
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]
        
      - name: Run tests
        run: |
          pytest -vv --tb=short
